sudo: required
language: c++
services:
  - docker

before_script:
- docker pull ralreegorganon/cddadockerwin

script:
- docker run --rm -v $TRAVIS_BUILD_DIR:/tmp ralreegorganon/cddadockerwin make RELEASE=1 TILES=1 SOUND=1 LUA=1 LOCALIZE=1 LUA_BINARY=lua5.3

git:
  depth: 5