sudo: required
language: c++
cache: ccache

git:
  depth: 5

matrix:
  include:
    # GCC 4.9
    - env: DOCKERIMAGE=gcc49

before_script:
- docker pull ralreegorganon/cddadocker:$DOCKERIMAGE

script: 
- docker run --rm -v $TRAVIS_BUILD_DIR:/tmp ralreegorganon/cddadocker:$DOCKERIMAGE make -j3 RELEASE=1 